#ifndef DEFINE_H
#define DEFINE_H
#define GET "GET"
#define POST "POST"
#define PUT "PUT" 
#define DELETE "DELETE"
#define SIGNUP "signup"
#define LOGIN "login"
#define FILMS "films"
#define FOLLOWERS "followers"
#define MONEY "money"
#define PUBLISHED "published"
#define REPLIES "replies"
#define COMMENTS "comments"
#define BUY "buy"
#define RATE "rate"
#define PURCHASED "purchased"
#define NOTIFICATIONS "notifications"
#define PUBLISHER "publisher"
#define CUSTOMER "customer"
#define TRUE_ANSWER "true"
#define FALSE_ANSWER "false"
#define EMAIL "email"
#define USERNAME "username"
#define PASSWORD "password"
#define AGE "age"
#define OK "OK"
#define YEAR "year"
#define LENGTH "length"
#define PRICE "price"
#define NAME "name"
#define DIRECTOR "director"
#define FILM_ID "film_id"
#define EDIT "edit"
#define EXIST "exist"
#define USER_ID "user_id"
#define FOLLOWE "followe"
#define REGISTER_FILM "register_film"
#define SPACE " "
#define DOT "."
#define LINE "|"
#define IN "in"
#define QUESTION_MARK "?"
#define BUY_FILM "buy_film"
#define RATE "rate"
#define COMMENT "comment"
#define NAME "name"
#define MIN_RATE "min_rate"
#define MIN_YEAR "min_year"
#define Max_YEAR "max_year"
#define FILM_ID_PRINT "Film Id"
#define FILM_NAME "Film Name"
#define FILM_LENGTH "Film Length"
#define FILM_PRICE "Film price"
#define FILM_RATE "Rate"
#define FILM_PRODUCTION_YEAR "Production Year"
#define FILM_DIRECTOR "Film Director"
#define USER_ID_PRINT "User Id"
#define USER_USERNAME "User Username"
#define USER_MAIL "User Email"
#define CONTENT "content"
#define DELETE_FILM "delete"
#define ID "ID"
#define DIRECTOR_OF_FILM "Director"
#define LENGTH_PRINT "Length"
#define YEAR_PRINT "Year"
#define SUMMARY "summary"
#define RATE_PRINT "Rate"
#define PRICE_PRINT "Price"
#define EQUAL "="
#define COMMENTS_PRINT "Comments"
#define SUMMARY_FILM "summary"
#define AMOUNT "amount"
#define COMMENT_ID "comment_id"
#define SCORE "score"
#define SEVEN 7
#define THIRTEEN 13
#define ELEVEN 11
#define SPACE_CHAR ' '
#define EIGHT 8
#define HUNDERED 100
#define EIGHTY 80
#define NINETY 90
#define NINTY_FIVE 95
#define DOT_CHAR '.'
#define DELETE_FILMS "delete_films"
#define DELETE_COMMENTS "delete_comments"
#define OUT "out"
#define LOGOUT "logout"
#define NOT_GET_MONEY 0
#define ADMIN "admin"
#define PUT_FILMS "put_films"
#define ZERO 0
#define FOUR 4
#endif