#ifndef DEFINE_H
#define DEFINE_H
#define SIGNUP "signup"
#define LOGIN "login"
#define MONEY "money"
#define PUBLISHED "published"
#define BUY "buy"
#define RATE "rate"
#define PUBLISHER "publisher"
#define CUSTOMER "customer"
#define TRUE_ANSWER "true"
#define FALSE_ANSWER "false"
#define EMAIL "email"
#define USERNAME "username"
#define PASSWORD "password"
#define AGE "age"
#define OK "OK"
#define YEAR "year"
#define LENGTH "length"
#define PRICE "price"
#define NAME "name"
#define DIRECTOR "director"
#define FILM_ID "film_id"
#define EXIST "exist"
#define SPACE " "
#define IN "in"
#define COMMENT "comment"
#define NAME "name"
#define DELETE_FILM "delete"
#define ID "ID"
#define OUT "out"
#define LOGOUT "logout"
#define FOUR 4
#define SPACELINE " / "
#define SUMMARY "summary"
#endif